passmenu: Fix spaces

diff --git a/bin/passmenu b/bin/passmenu
--- a/bin/passmenu
+++ b/bin/passmenu
@@ -6,34 +6,34 @@ wl_copy_args=("-o")
 wofi_args=("")
 
 usage() {
-	echo -e "Wofi based interface for pass
+    echo -e "Wofi based interface for pass
 Usage:
 wofipassmenu [Options]
-Options:
-	-h	Help
-	-n	Don't use one-time copy (by default copy will be deleted after first paste, but some clients (XWayland) can be break)
-	-p	Use the \"primary\" clipboard instead of the regular clipboard
-	"
+    Options:
+    -h	Help
+    -n	Don't use one-time copy (by default copy will be deleted after first paste, but some clients (XWayland) can be break)
+    -p	Use the \"primary\" clipboard instead of the regular clipboard
+    "
 }
 
 
 while getopts ":hpn" option; do
-	echo $option
-	case $option in
-		h )
-			usage
-			exit 0
-			;;
-		n )
-			wl_copy_args=("${wl_copy_args[@]/-o}")
-			;;
-		p )
-			wl_copy_args=("${wl_copy_args[@]} -p")
-			;;
-		\? )
-			usage
-			exit 1
-	esac
+    echo $option
+    case $option in
+        h )
+            usage
+            exit 0
+            ;;
+        n )
+            wl_copy_args=("${wl_copy_args[@]/-o}")
+            ;;
+        p )
+            wl_copy_args=("${wl_copy_args[@]} -p")
+            ;;
+        \? )
+            usage
+            exit 1
+    esac
 done
 
 shift $(expr $OPTIND - 1 )
@@ -51,7 +51,7 @@ password=$(printf '%s\n' "${password_files[@]}" | wofi -m -i -p "Password name" 
 
 pass show "$password" | head -n1 | wl-copy $wl_copy_args 2>/dev/null
 if [[ $? != 0 ]]; then
-	echo "Some error has occured"
+    echo "Some error has occured"
 else
-	echo "Password copyied to clipboard"
+    echo "Password copyied to clipboard"
 fi
